apiVersion: apps/v1
kind: Deployment
metadata:
  name: w3schoolclone
  namespace: default
  labels:
    app: w3schoolclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w3schoolclone
  template:
    metadata:
      labels:
        app: w3schoolclone
    spec:
      containers:
        - name: w3schoolclone
          image: liberosis8803/w3schoolclone
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: w3schoolclone-service
  namespace: default
spec:
  selector:
    app: w3schoolclone
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: NodePort
