name: Build and Publish Docker Image to Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  Dockerhub:
    name: 'Build and Publish Docker Image to Dockerhub'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Code
      uses: actions/checkout@v4

    # Login to Docker Hub
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Docker image to Docker Hub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: liberosis8803/w3schoolclone
        build-args: |
          FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
