name: 'Build and Publish Docker Image to Dockerhub'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  Dockerhub:
    name: 'Build and Publish Docker Image to Dockerhub'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and push Docker Image
      run: |
        docker build --build-arg FIREBASE_TOKEN=${{secrets.FIREBASE_TOKEN}} -t liberosis8803/w3schoolclone .
        docker push liberosis8803/w3schoolclone
